# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccdejavu" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "8dcc3c45b739125bfab6960498bec0d331aeec7ffe912047ac8907e944961901"
      url "https://github.com/wjames111/ccdejavu/releases/download/v#{version}/ccdejavu-v#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "e79ec92c26dbabb97f41416d4d17fba816e9775475286d7aef1ac83c0e355a01"
      url "https://github.com/wjames111/ccdejavu/releases/download/v#{version}/ccdejavu-v#{version}-darwin-amd64.tar.gz"
    end
  end

  name "ccdejavu"
  desc "Keep Claude desktop app chats in sync across the accounts you link"
  homepage "https://github.com/wjames111/ccdejavu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccdejavu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccdejavu"]
    end
  end

  # No zap stanza required
end
