# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccdejavu" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "41f3ab96eb38e1a42efe8d92db3b1e20837f1773ea953777d461231689d4bd61"
      url "https://github.com/wjames111/ccdejavu/releases/download/v#{version}/ccdejavu-v#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "bb76d900dcc7c2984abfbca4a8ec6932622705e7adb8085479ce9ec4becefa6b"
      url "https://github.com/wjames111/ccdejavu/releases/download/v#{version}/ccdejavu-v#{version}-darwin-amd64.tar.gz"
    end
  end

  name "ccdejavu"
  desc "Keep Claude desktop app chats in sync across every account on your Mac"
  homepage "https://github.com/wjames111/ccdejavu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccdejavu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccdejavu"]
    end
  end

  # No zap stanza required
end
